### ISSUE TITLE
email() does not work

### ISSUE THREAD

**Issue by myselfghost** [bungle/lua-resty-validation#2]
bb@gil,@gil   can be matched

**Comment by bungle** [comment]
`bb@gil` is pefectly valid email address `@gil` may not be, so that should be fixed.

**Comment by bungle** [comment]
Okay I just pushed latest version of email validator. I may add something like strict argument to email function if you really want to check only addresses that contain at least one dot in domain part of the email address, But by definition even this is valid email address `e@m`.

**Comment by myselfghost** [comment]
thanks, bungle
