### ISSUE TITLE
validation.lua typo?

### ISSUE THREAD

**Issue by bumi001** [bungle/lua-resty-validation#8]
Hi, Line 20 currently reads as:

local len = utf8 and utf8.len or function(s) return select(2, gsub(s, '[^\x80-\xC1]', '')) end

Should that be:

local len = utf8 and utf8.len or function(s) return select('#', gsub(s, '[^\x80-\xC1]', '')) end

Essentially, the first parameter to select is the potential problem.

**Comment by bungle** [comment]
@bumi001, does this fix the issue:
https://github.com/bungle/lua-resty-validation/pull/9

**Comment by bumi001** [comment]
Thanks. Both versions work. I realized that I had a misunderstanding.
